version: "3"
services:
  app:
    restart: "always"
    image: chialab/php:7.3-fpm
    command: bash -c "composer install && php -S 0.0.0.0:8000 index.php"
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
